apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.credentials.admin.username }}
  password: {{ .Values.credentials.admin.password | b64enc }}
  email: {{ .Values.credentials.admin.email }}