replicaCount: 1

namespace: ci-cd

image:
  repository: jfrog.it-academy.by/public/jenkins-ci
  tag: aleksey_do
  pullPolicy: IfNotPresent

jenkins:
  numExecutors: 2
  adminEmail: "pluhin@gmail.com"
  url: "http://jenkins.k8s-XX.sa"
  resources:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 3
      memory: 3Gi
  ports:
    http: 8080
    jnlp: 50000

credentials:
  admin:
    username: admin
    password: pass
  github:
    username: git_hub_user
    password: XXXXXXXXXXX
    id: some_randome

persistence:
  nfs:
    server: 192.168.37.105
    path: /mnt/IT-Academy/nfs-data/sa2-30-24/alex_agd/jenkins

ingress:
  enabled: true
  className: nginx
  host: jenkins.k8s-5.sa
  servicePort: 8080
  path: /
  pathType: Prefix

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80





autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
